"""Package the isolated low-view experiment as full videos and a synced review page."""
import argparse
import json
import pickle
import subprocess
from pathlib import Path

import cv2
import numpy as np

from netcast_tennisvision.streaming.live_experiment import _ffmpeg


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--out', type=Path, required=True)
    parser.add_argument('--source', type=Path, required=True)
    args = parser.parse_args()
    summary = {}
    for mode in ('baseline', 'roi'):
        scene = json.loads((args.out / mode / 'scene3d.json').read_text(encoding='utf-8'))
        # Trusted local artifact generated by our experiment, not an uploaded pickle.
        with (args.out / mode / 'analysis.pkl').open('rb') as stream:
            analysis = pickle.load(stream)
        summary[mode] = dict(
            frames=scene['n_frames'], fps=scene['fps'], bounces=len(scene['bounces']),
            tracked=sum(isinstance(f.get('b'), list) for f in scene['frames']),
            detected=sum(bool(f.get('ball_seen')) for f in analysis['frames_meta']),
            inferred=scene.get('experimental_occluded_landings', []),
        )
    video = args.out / 'flat_deemo_low_view.mp4'
    subprocess.run([_ffmpeg(), '-y', '-loglevel', 'error',
                    '-i', str(args.out / 'roi/annotated_clip.mp4'), '-i', str(args.source),
                    '-map', '0:v:0', '-map', '1:a:0?', '-c:v', 'copy', '-c:a', 'aac',
                    '-movflags', '+faststart', str(video)], check=True)
    cap = cv2.VideoCapture(str(video))
    count = 0
    thumbs = []
    targets = [round(t*summary['roi']['fps']) for t in (10, 45, 85, 125, 165, 220)]
    while cap.grab():
        if count in targets:
            ok, frame = cap.retrieve()
            if ok:
                thumb = cv2.resize(frame, (480, 272))
                cv2.putText(thumb, f'{count/summary["roi"]["fps"]:.1f}s', (8, 265),
                            cv2.FONT_HERSHEY_SIMPLEX, .7, (255, 255, 255), 2)
                thumbs.append(thumb)
        count += 1
    cap.release()
    assert count == summary['roi']['frames'], (count, summary['roi']['frames'])
    if len(thumbs) == 6:
        cv2.imwrite(str(args.out / 'review_contact_sheet.jpg'),
                    np.vstack([np.hstack(thumbs[:3]), np.hstack(thumbs[3:])]))
    summary['decoded_output_frames'] = count
    (args.out / 'summary.json').write_text(json.dumps(summary, indent=2), encoding='utf-8')
    page = '''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>平视角落地实验 · flat_deemo</title><style>
body{margin:0;background:#16131f;color:#f6f3ff;font:16px system-ui;padding:24px}main{max-width:1500px;margin:auto}h1{font-size:26px}p{color:#c9c3d6;line-height:1.7}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}video{width:100%;background:#000;border-radius:12px}button,a{background:#7735cf;color:white;border:0;border-radius:8px;padding:10px 16px;text-decoration:none;cursor:pointer}section{background:#252030;padding:16px;border-radius:14px}#events button{margin:5px}small{color:#b8aecb}@media(max-width:900px){.grid{grid-template-columns:1fr}}
</style><main><h1>平视角落地实验 · flat_deemo</h1>
<p>完整视频约 3 分 53 秒，原始 30fps。实验：远端局部补充检测＋遮挡前后轨迹判断。未修改正式高视角分析流程。</p>
<p>紫点是球的位置，没有拖尾。黄色区域和小地图沿用已定位落地；橙色英文提示表示“推断发生反弹，位置未知”，不会添加小地图落点。该实验尚未完成人工准确率验收。</p>
<div class="grid"><section><h2>原方案</h2><video id="base" src="baseline/annotated_clip.mp4" controls playsinline preload="metadata" muted></video><p id="oldStats"></p></section>
<section><h2>平视角实验方案</h2><video id="trial" src="flat_deemo_low_view.mp4" controls playsinline preload="metadata"></video><p id="newStats"></p></section></div>
<p><button id="play">同步播放 / 暂停</button> <a href="flat_deemo_low_view.mp4">单独打开实验视频</a> <a href="flat_deemo_low_view.mp4" download>下载完整视频</a></p>
<p><small>实验视频为主时间轴，拖动右侧进度条同步对照。下面的数量仅是输出计数，不代表准确率。</small></p>
<div id="events"></div></main><script>
const summary=SUMMARY_JSON;
const base=document.getElementById('base'),trial=document.getElementById('trial');
function stats(s){return `球位置帧数 ${s.tracked}/${s.frames}（真实检测 ${s.detected}）；已定位落地 ${s.bounces} 次；额外遮挡反弹推断 ${s.inferred.length} 次`;}
document.getElementById('oldStats').textContent=stats(summary.baseline);document.getElementById('newStats').textContent=stats(summary.roi);
trial.addEventListener('seeking',()=>{base.currentTime=trial.currentTime});trial.addEventListener('play',()=>{base.currentTime=trial.currentTime;base.play().catch(()=>{})});trial.addEventListener('pause',()=>base.pause());trial.addEventListener('ratechange',()=>{base.playbackRate=trial.playbackRate});trial.addEventListener('timeupdate',()=>{if(Math.abs(base.currentTime-trial.currentTime)>.15)base.currentTime=trial.currentTime});
document.getElementById('play').onclick=()=>trial.paused?trial.play():trial.pause();
const events=document.getElementById('events');summary.roi.inferred.forEach(e=>{const b=document.createElement('button');b.textContent=`遮挡推断 ${e.time_s.toFixed(2)}s`;b.onclick=()=>{trial.currentTime=Math.max(0,e.time_s-1);trial.play()};events.appendChild(b)});
</script></html>'''.replace('SUMMARY_JSON', json.dumps(summary))
    (args.out / 'review.html').write_text(page, encoding='utf-8')
    print(json.dumps(summary, ensure_ascii=False), flush=True)


if __name__ == '__main__':
    main()
